---
title: "Tables for Roughy Report 2019"
author: "Caroline Sutton"
date: "19/04/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)

#Load libraries
library(tidyverse)
library(ggplot2)
library(scales)
library(ggpubr)
library(Rmisc)
library(dplyr)
library(devEMF)
library(tidyr)
library(kableExtra)
library(knitr)
library(cowplot)
library(gridExtra)
library(flextable)
library(officer)

#read in tidy data from results folder
Roughy <- read_csv("Results/OREastern_Tidy_87to2019.csv", col_types = list(ShotWeight_kg = col_double(),
                                                                           mark = col_character()
                                                                           ))

#remame and select columns

Roughy <- Roughy %>% 
  mutate(Length =round(SLadj_cm)) %>% #round values for length in cm 2019 was to nearest mm
  mutate(Ground = Area_MS) %>%
  drop_na(Ground) %>% 
  drop_na(Length) %>% 
  drop_na(sex) %>% 
  select(Ground, year, Shot, Date,sex,stage, Length,ShotWeight_kg, weight_kg)
```

## Table 2.3
```{r table 2.3, echo=FALSE}
# fitler data for 2019
Roughy_2019 <- Roughy %>% 
  filter(year==2019)

Roughy_2019_sum <- Roughy %>% 
  filter(year==2019) %>% 
  dplyr::group_by(Ground,Shot,Date,ShotWeight_kg,sex) %>% 
  dplyr::summarise(num_rows = n()) %>% 
  spread(sex,num_rows) %>% 
  mutate(`Total` = F + M) 

# creating ground/ and survey totals for:

#St Helens
TSH <- Roughy_2019_sum %>% 
  filter(Ground == "St Helens") %>% 
  dplyr::group_by(Ground) %>% 
  dplyr::summarise(ShotWeight_kg =sum(ShotWeight_kg, na.rm = TRUE), F= sum(F), M = sum(M), Total =sum(Total)) %>% 
  mutate(Ground = "St Helens Total")
#St Patricks
TSP <- Roughy_2019_sum %>% 
  filter(Ground == "St Patricks") %>% 
  dplyr::group_by(Ground) %>% 
  dplyr::summarise(ShotWeight_kg =sum(ShotWeight_kg, na.rm = TRUE), F= sum(F), M = sum(M), Total =sum(Total)) %>% 
  mutate(Ground = "St Patricks Total")

# totals for SH and SP
TotalS <- Roughy_2019_sum %>% 
  summarise(ShotWeight_kg = sum(ShotWeight_kg, na.rm = TRUE), F= sum(F), M = sum(M), Total =sum(Total)) %>% 
  mutate(Ground = "Survey Total")

#bind the shot and totals 
Roughy_2019_sumtotals <- bind_rows(Roughy_2019_sum, TSH, TSP,TotalS) %>% # put all together for totals
  dplyr::rename("Shot Weight (kg" = ShotWeight_kg, "Total Nos Fish" = Total)
  
OR2019_sum_g <- as_grouped_data(x=Roughy_2019_sumtotals,groups = c("Ground")) %>% 
  mutate(Amount = if_else(is.na(Ground), "", as.character(Ground)))
        
t2.3 <- autofit(flextable(Roughy_2019_sumtotals))
t2.3 <- theme_booktabs(t2.3)
t2.3 <- align( t2.3, align = "center", part = "all" )
t2.3


#t2.3b <- as_flextable((OR2019_sum_g))
#t2.3b
  
```


## Table 2.4

```{r table 2.4, echo=FALSE}
Roughy_1 <- Roughy %>% 
  mutate(GbyS= paste(Ground,sex,sep = "_")) %>%  #new variable to combine Ground and sex 
  group_by(GbyS) %>% 
  mutate(sumsum = cumsum(Length))


#create function to find the mode
Mode <- function(x) {
    if (is.numeric(x)) {
        x_table <- table(x)
        return(as.numeric(names(x_table)[which.max(x_table)]))
        }
}
Roughy_mode <- Roughy_1 %>% 
  dplyr::group_by(year,GbyS) %>%
  dplyr::summarise(Mode = Mode(x = Length))%>%
  spread(GbyS, Mode) 
#create counts
Roughy_nos <- Roughy_1 %>% 
  dplyr::group_by(year, GbyS) %>%
  dplyr::summarise(Numbers = n())%>%
  spread(GbyS, Numbers)

#bind the mode and counts
R_Mode_Count <-  cbind(Roughy_mode,Roughy_nos)%>%
  select(-6)#remove the year1 colomn

  R_Mode_Count_order <- R_Mode_Count[,c(1,2,6,3,7,4,8,5,9)]  # order the columns
  
  
t2.4 <- flextable(R_Mode_Count_order)
#t2.4 <- align(t2.4, align = "center", part = "all")
t2.4 <- set_header_labels(t2.4
                          ,year =""
                          ,'St Helens_F'="St Helens, Female",'St Helens_F1'="St Helens, Female"
                          ,'St Helens_M'="St Helens, Male", 'St Helens_M1'="St Helens, Male"
                          , 'St Patricks_F'= "St Patricks, Female", 'St Patricks_F1'="St Patricks, Female"
                          , 'St Patricks_M'= "St Patricks, Male", 'St Patricks_M1' ="St Patricks, Male")
t2.4 <- merge_at(t2.4, i=1, j=2:3, part = "header")
t2.4 <- merge_at(t2.4, i=1, j=4:5, part = "header")  
t2.4 <- merge_at(t2.4, i=1, j=6:7, part = "header")
t2.4 <- merge_at(t2.4, i=1, j=8:9, part = "header")
t2.4 <- add_header_row(t2.4, top=FALSE,
                       values = c("Year", "Mode","Nos. Fish", "Mode","Nos. Fish", "Mode","Nos. Fish"
                                  , "Mode","Nos. Fish"))
t2.4 <- theme_booktabs(t2.4)
t2.4 <- autofit(t2.4)
t2.4 <- align( t2.4, align = "center", part = "all" )
t2.4

```

### Table 2.5

```{r table2.5, out.width='100%', echo = FALSE} 


#spread the weight by sex
Roughy_2019_shotweight <- Roughy_2019 %>% 
  dplyr::group_by(Ground,sex,Shot) %>% 
  dplyr::summarise('Average weight' = round(mean(weight_kg, na.rm = TRUE),digits = 2)) %>% 
  spread(sex,'Average weight') %>% 
  rename(c("F"="fw","M"="mw"))

#spread the SD by sex
Roughy_2019_ShotweightSD <- Roughy_2019 %>% 
  dplyr::group_by(Ground,sex,Shot) %>% 
  dplyr::summarise(SD = round(sd(weight_kg, na.rm = TRUE),digits = 2)) %>% 
  spread(sex, SD) %>% 
   rename(c("F"="fsd","M"="msd"))

#spread the nos by sex
Roughy_2019_Shotnos <-Roughy_2019 %>% 
  dplyr::group_by(Ground,sex,Shot) %>% 
  dplyr::summarise(nos = n()) %>% 
  spread(sex, nos)

#bind weight, sd and nos, remove dupicate columns

t2.5 <- cbind(Roughy_2019_shotweight,Roughy_2019_ShotweightSD, Roughy_2019_Shotnos) %>% 
  select(-5,-6,-9,-10,-13,-14)
  #rename(c("fw" ="Avg weight (kg)","fsd"= "SD", "F" = "nos F", "mw"="Avg Weight (kg)","M"="nos M"))
t2.5 <- t2.5[ ,c(1,2,3,5,7,4,6,8)] 
t2.5 <- flextable(t2.5) %>%
  add_header_row( values = c("","","","Females","","","Males","")) %>% 
  set_header_labels("Ground"="Ground", "Shot"="Shot", "fw"= "weight (kg)", "fsd"="SD", "F"="nos",
                    "mw"="weight (kg)", "msd"="SD", "M"= "nos") %>% 
 theme_booktabs() %>% 
  autofit() %>% 
  align(align = "center", part = "all")

t2.5


```